### PR TITLE
Blacklight 7.33 Upgrade: Fix articles plus view position

### LINKED ISSUE #1388: Articles+ gem should appear after 3rd result
In the testing environment for Blacklight 7.33 the Articles+ gem appears after the 2nd result. It should appear after the 3rd result, as it does in production.

**Example from production:**

### PR DESCRIPTION
**Pull request by abelemlih**
Fixes #1388

### CODE REVIEW

File: app/assets/javascripts/alternate_catalog.js [hunk 1]
```diff
@@ -3,18 +3,19 @@
...
-
     },
 
-    injectAlternateCatalogInotResults: function() {
-      var $documents = $('#documents');
-      var afterThird = $documents.find('.document-position-2').after(this.container);
+    injectAlternateCatalogInotResults: function () {
+      var $documents = $("#documents");
+      var afterThird = $documents
+        .find(".document-position-3")
```
Comment (abelemlih) [inline app/assets/javascripts/alternate_catalog.js:17]: The main change is switching from `.find(".document-position-2")` to `.find(".document-position-3")` since the counter used in Blacklight switched from starting at 0 to starting at 1. The rest of the changes are just linter recommendations.

**Review by bwatson78 — APPROVED** [review]
